export const FETCH_BEERS = "FETCH_BEERS";
export const FETCH_BEERS_FAILED = "FETCH_BEERS_FAILED";

export const FETCH_FULL_BEER = 'FETCH_FULL_BEER';
export const REMOVE_FULL_BEER = 'REMOVE_FULL_BEER';
export const ADD_BEER_ID = 'ADD_BEER_ID';

export const FAVORITE_BEER = 'FAVORITE_BEER';
export const UNFAVORITE_BEER = 'UNFAVORITE_BEER';
export const SET_FAVORITE_BEER = 'SET_FAVORITE_BEER';
export const FETCH_FAVORITES_START = 'FETCH_FAVORITES_START';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';

export const SEARCH_FOR_BEER = 'SEARCH_FOR_BEER';